name: alfurqan
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+7

environment:
  sdk: ^3.6.1

dependencies:
  audioplayers: ^6.4.0
  connectivity_plus: ^6.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  geolocator: ^12.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  hijri: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  hugeicons: ^0.0.7
  intl: ^0.18.1
  intl_translation: ^0.19.0
  just_audio: ^0.9.46
  loading_animation_widget: ^1.3.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.0.15
  timeago: ^3.7.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/audio/nufaisAthan.mp3

  fonts:
    - family: UthmanicHafs
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf

    - family: newQuran
      fonts:
        - asset: assets/fonts/newquran.ttf

    - family: UthmanTN1
      fonts:
        - asset: assets/fonts/UthmanTN1-Ver10.otf

    - family: BalooBold
      fonts:
        - asset: assets/fonts/Baloo-Bold.ttf

    - family: BalooReg
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf

    - family: Kitab
      fonts:
        - asset: assets/fonts/Kitab-Reg.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
